version: '3'
services:
  openvpn:
    container_name: openvpn1
    restart: always
    build: .
    image: openvpn1
    volumes:
      - ./volumes:/etc/openvpn
    network_mode: host
    ports:
      - 1194:1194/udp
    privileged: true
